apiVersion: v1
kind: Service
metadata:
  name: hello-backend
  labels:
    app.kubernetes.io/name: hello-backend
spec:
  type: ClusterIP            # raggiungibile SOLO dentro il cluster
  selector:
    app.kubernetes.io/name: hello-backend
  ports:
    - name: http
      port: 8080
      targetPort: http       # riferimento per NOME: se cambi la porta del container, il Service segue
