apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-backend-config
data:
  APP_ENV: "base"
  GREETING: "Ciao dal backend Java su Kubernetes"
  OLLAMA_URL: "http://ollama.ai.svc.cluster.local:11434"
  OLLAMA_MODEL: "qwen2.5:1.5b"
  SHUTDOWN_DELAY_SECONDS: "5"
  SHUTDOWN_GRACE_SECONDS: "10"
