apiVersion: v1
kind: Namespace
metadata:
  name: hello
  labels:
    # Pod Security Admission: il profilo "restricted" rifiuta Pod privilegiati, root, capabilities extra...
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
