{{- if .Values.backend.pdb.enabled }}
{{- $ctx := dict "ctx" . "component" "backend" -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hello.componentName" $ctx }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello.labels" $ctx | nindent 4 }}
spec:
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "hello.selectorLabels" $ctx | nindent 6 }}
{{- end }}
