{{- if .Values.serviceMonitor.enabled }}
{{- $ctx := dict "ctx" . "component" "backend" -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hello.componentName" $ctx }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello.labels" $ctx | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "hello.selectorLabels" $ctx | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
