apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hello.componentName" (dict "ctx" . "component" "backend") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello.labels" (dict "ctx" . "component" "backend") | nindent 4 }}
automountServiceAccountToken: false
