apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-agent-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: lab
  source:
    repoURL: https://github.com/cyb3rdem0n/k8s-platform-lab.git
    targetRevision: main
    path: k8s/apps/ai/agent-rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated: { prune: true, selfHeal: true }
